package org.computer.auth.service.bean;

/**
 * Pricing generated by MyEclipse Persistence Tools
 */

public class Pricing implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long	serialVersionUID	= -2448823958641907704L;
	private Integer	id;
	private Integer	price;
	private Short	sortOrder;
	private String	active;

	// Constructors

	/** default constructor */
	public Pricing() {}

	/** full constructor */
	public Pricing(Integer id, Integer price, Short sortOrder, String active) {
		this.id = id;
		this.price = price;
		this.sortOrder = sortOrder;
		this.active = active;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	public Short getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(Short sortOrder) {
		this.sortOrder = sortOrder;
	}

	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	} 
	
	public Pricing copyOf() {
		Pricing copy = new Pricing(this.id, this.price, new Short(this.sortOrder), this.active);
		return copy;
	}

}